import {createRequire} from 'node:module';import {mkdir,writeFile} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');await mkdir(path.join(root,'.preview'),{recursive:true});
const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('/missing/'))errors.push(r.status()+' '+r.url());});
const base='http://127.0.0.1:4173';
async function loadImages(){await page.locator('img').evaluateAll(async els=>{els.forEach(i=>i.loading='eager');await Promise.all(els.map(i=>i.decode()));});}
await page.goto(base);await page.waitForLoadState('networkidle');await loadImages();await page.screenshot({path:path.join(root,'.preview/home-desktop.png'),fullPage:true});
if(!await page.locator('img').evaluateAll(els=>els.every(i=>i.complete&&i.naturalWidth)))throw Error('An image failed');
await page.evaluate(()=>scrollTo(0,350));await page.waitForTimeout(120);const transforms=await page.locator('[data-depth]').evaluateAll(els=>els.map(el=>el.style.transform));if(new Set(transforms).size!==3)throw Error('Parallax layers not distinct');
await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(100);if(!await page.locator('[data-depth]').evaluateAll(els=>els.every(el=>getComputedStyle(el).transform==='none')))throw Error('Reduced motion ignored');await page.emulateMedia({reducedMotion:'no-preference'});
await page.goto(base+'/journal/');await page.locator('#filter-system').selectOption('engine');if(await page.locator('#journal-records article:visible').count()<1)throw Error('Engine records missing');await page.locator('#filter-type').selectOption('Archive');if(await page.locator('#journal-empty').isHidden())throw Error('Empty state missing');await page.locator('#filter-system').selectOption('all');await page.locator('#filter-type').selectOption('Archive');if(await page.locator('#journal-records article:visible').count()!==1)throw Error('Journal filter failed');await page.reload();if(await page.locator('#filter-type').inputValue()!=='Archive')throw Error('Filter URL state failed');
await page.goto(base+'/explore/');await page.getByRole('button',{name:'Earlier concept'}).click();if(!(await page.locator('#view-caption').textContent()).includes('Archive'))throw Error('View change failed');
await page.goto(base+'/systems/hull-hydrodynamics/');await page.waitForLoadState('networkidle');await page.locator('[data-mass]').selectOption('80');if(!(await page.locator('[data-chart-readout]').textContent()).includes('0.1318'))throw Error('Data readout incorrect');
const graphics=await page.locator('.chart,.bare-visual').evaluateAll(els=>els.every(el=>getComputedStyle(el).backgroundColor==='rgba(0, 0, 0, 0)'));if(!graphics)throw Error('Graphic background box found');await loadImages();await page.screenshot({path:path.join(root,'.preview/hull-desktop.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});await page.goto(base);await page.waitForLoadState('networkidle');await loadImages();await page.screenshot({path:path.join(root,'.preview/home-mobile.png'),fullPage:true});await page.getByRole('button',{name:'Menu',exact:true}).click();await page.locator('#primary-nav').getByRole('link',{name:'Journal',exact:true}).click();if(!page.url().endsWith('/journal/'))throw Error('Mobile navigation failed');
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});for(const url of ['/','/systems/','/systems/hull-hydrodynamics/','/journal/','/history/','/roadmap/','/back/','/journal/early-design-archive/','/journal/rider-interface-archive/','/journal/surface-investigation/','/systems/deck/','/systems/controls/','/journal/engine-as-a-system/','/journal/nozzle-area-study/','/journal/battery-and-starting/','/journal/from-brief-to-test/']){await page.goto(base+url);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error(`Overflow ${width} ${url}`);}}
await page.goto(base+'/journal/nozzle-area-study/');await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(root,'.preview/nozzle-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'.preview/nozzle-mobile.png'),fullPage:true});
const bad=await page.goto(base+'/missing/');if(bad.status()!==404)throw Error('Missing page status wrong');
if(errors.length)throw Error(errors.join('\n'));await writeFile(path.join(root,'.preview/browser-check.json'),JSON.stringify({passed:true,viewports:[320,390,768,1440],checks:['images','navigation','journal filters and URL state','archive view selection','source data readout','transparent graphic surfaces','parallax','reduced motion','404','no overflow'],errors},null,2));console.log('Browser checks passed; screenshots saved in .preview.');await browser.close();
