import {sections, readingGroups, descriptiveTitles, groupId, sectionFor, readingSequence, keepLocal, withoutSectionLinks} from './navigation.mjs';
import {geometryFeature,geometryVisual} from './geometry-gallery.mjs';
import {developmentVisual} from './development-visuals.mjs';
import {engineeringFeature,engineeringVisual} from './engineering-gallery.mjs';
import {hullGraphics,systemVisuals,archiveSpread} from './visuals.mjs';
import {readFile,writeFile,mkdir,cp} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const site=JSON.parse(await readFile(path.join(root,'content/site.json'),'utf8'));
const allUpdates=[JSON.parse(await readFile(path.join(root,'content/cfd20-completion.json'),'utf8')),...JSON.parse(await readFile(path.join(root,'content/geometry-studies.json'),'utf8')),...JSON.parse(await readFile(path.join(root,'content/engineering-studies.json'),'utf8')),...JSON.parse(await readFile(path.join(root,'content/updates.json'),'utf8'))];
allUpdates.sort((a,b)=>(b.date||'').localeCompare(a.date||''));
const updates=allUpdates.filter(u=>u.status==='published');
for(const u of updates)u.title=descriptiveTitles[u.slug]??u.title;
const points=JSON.parse(await readFile(path.join(root,'content/displacement.json'),'utf8'));
const out=path.join(root,'dist');await mkdir(out,{recursive:true});
// A fresh build owns only files recorded in its previous manifest; drafts never enter output.
const {rm}=await import('node:fs/promises');
try{for(const file of JSON.parse(await readFile(path.join(out,'build-manifest.json'),'utf8'))){const dest=path.resolve(out,file);if(!dest.startsWith(out+path.sep))throw Error('Unsafe build manifest');await rm(dest,{force:true});}}catch(e){if(e.code!=='ENOENT')throw e;}
await cp(path.join(root,'public'),out,{recursive:true});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=(name,alt,cls='',eager=false)=>`<img class="${cls}" src="/assets/${name}" alt="${esc(alt)}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async" width="1600" height="850">`;
const arrow='<span aria-hidden="true">↗</span>';
function flow(id='flow'){return `<svg class="flow-art" viewBox="0 0 1000 500" aria-hidden="true"><defs><linearGradient id="${id}"><stop stop-color="#24b8ff" stop-opacity="0"/><stop offset=".2" stop-color="#24b8ff" stop-opacity=".25"/><stop offset=".8" stop-color="#24b8ff" stop-opacity=".2"/><stop offset="1" stop-color="#24b8ff" stop-opacity="0"/></linearGradient></defs>${Array.from({length:20},(_,j)=>`<path d="${Array.from({length:100},(_,i)=>{const t=i/99;return `${i?'L':'M'}${(t*1000).toFixed(1)},${(95+j*11+Math.sin(t*Math.PI)*Math.sin(t*Math.PI*1.5+j*.065)*125).toFixed(1)}`}).join(' ')}" fill="none" stroke="url(#${id})"/>`).join('')}<path d="M140 380h12m-6-6v12M830 80h12m-6-6v12" stroke="#285061"/></svg>`;}
const link=(url,label,cls='text-link')=>`<a class="${cls}" href="${url}">${label} ${arrow}</a>`;
const eyebrow=t=>`<p class="eyebrow">${t}</p>`;
function card(u){return `<article class="journal-item" data-system="${u.systems.join(' ')}" data-kind="${u.type}">${u.hero?`<a class="journal-image" href="/journal/${u.slug}/">${img(u.hero,u.title)}</a>`:`<div class="journal-type" aria-hidden="true">${u.revision}</div>`}<div class="meta">${u.evidence} · ${u.dateLabel}</div><h3><a href="/journal/${u.slug}/">${u.title}</a></h3><p>${u.summary}</p>${link('/journal/'+u.slug+'/','Read development note')}</article>`;}
function chart(){const rr=points.filter(p=>p.achievable);return `<div class="chart" data-chart><h3>Level-attitude displacement</h3><div class="chart-legend"><span>● Seawater · 1,025 kg/m³</span><span>○ Freshwater · 998 kg/m³</span></div><svg viewBox="0 0 700 360" role="img" aria-label="Level immersion in metres against requested mass in kilograms. Two calculated curves for freshwater and seawater."><text x="10" y="22" class="axis-title">Level immersion (m)</text>${[0,.04,.08,.12,.16].map(v=>`<line x1="62" y1="${290-v/.16*235}" x2="677" y2="${290-v/.16*235}" class="gridline"/><text x="12" y="${295-v/.16*235}">${v.toFixed(2)}</text>`).join('')}${[0,20,40,60,80].map(v=>`<text x="${62+v/80*615}" y="316" text-anchor="middle">${v}</text>`).join('')}${[998,1025].map(rho=>`<polyline class="curve density-${rho}" points="${rr.filter(r=>r.density===rho).map(r=>`${62+r.mass/80*615},${290-r.immersion/.16*235}`).join(' ')}"/>`).join('')}<text x="370" y="349" text-anchor="middle" class="axis-title">Requested mass (kg)</text><circle class="chart-point" cx="369.5" cy="186.5" r="5"/></svg><div class="chart-controls"><label>Inspect source sample <select data-mass>${rr.filter(r=>r.density===1025).map(r=>`<option value="${r.mass}" ${r.mass===40?'selected':''}>${r.mass} kg</option>`).join('')}</select></label><label>Water <select data-density><option value="1025">Seawater · 1,025 kg/m³</option><option value="998">Freshwater · 998 kg/m³</option></select></label></div><p class="chart-readout" data-chart-readout role="status">40 kg → 0.0705 m level immersion in seawater.</p><p class="caption">H0 R03 · source samples connected, no extrapolation. 100 kg is unachievable in both source series and is not plotted. No uncertainty band supplied.</p><details><summary>View the numerical data</summary><div class="table-scroll"><table><caption>Source samples, including unachievable requests</caption><thead><tr><th scope="col">Mass (kg)</th><th scope="col">Freshwater immersion (m)</th><th scope="col">Seawater immersion (m)</th></tr></thead><tbody>${points.filter(r=>r.density===998).map(r=>`<tr><th scope="row">${r.mass}</th><td>${r.achievable?r.immersion.toFixed(5):'Unachievable'}</td><td>${points.find(s=>s.density===1025&&s.mass===r.mass)?.immersion?.toFixed(5)??'Unachievable'}</td></tr>`).join('')}</tbody></table></div></details></div>`;}
const pageIntro=(tag,title,text)=>`<section class="page-intro wrap">${eyebrow(tag)}<h1>${title}</h1><p class="lead">${text}</p></section>`;
function layout(title,body,current='/'){const section=sectionFor(current);const navigation=current==='/'?sections:[['/','Home'],...(section?[section]:[])];return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${esc(title)} | Wahoo Racing</title>${current.includes("/studies/")?`<link rel="canonical" href="https://www.wahooracing.com/journal/${current.split("/studies/")[1]}">`:''}<meta name="description" content="${esc(site.description)}"><link rel="icon" type="image/png" href="/assets/brand/wahoo-black.png"><link rel="icon" type="image/png" href="/assets/brand/wahoo-white.png" media="(prefers-color-scheme: dark)"><link rel="stylesheet" href="/styles.css"><script src="/app.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header wrap"><a class="brand" href="/" aria-label="Wahoo Racing home"><img src="/assets/brand/wahoo-white.png" alt="Wahoo" width="1732" height="2798"><span>RACING<small>JETBOARD DEVELOPMENT</small></span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-nav">Menu</button><nav id="primary-nav" aria-label="Main navigation">${navigation.map(([url,name])=>`<a href="${url}" ${current===url?'aria-current="page"':''}>${name}</a>`).join('')}</nav></header><main id="main">${body}</main><footer class="site-footer wrap"><div><a class="footer-brand" href="/" aria-label="Wahoo Racing home"><img src="/assets/brand/wahoo-name-white.png" alt="Wahoo" width="2798" height="400"></a><p>The geometry. The decisions. The evidence.</p></div><div>${current==='/'?sections.map(([url,name])=>`<a href="${url}">${name}</a>`).join(''):`<a href="/">Home · choose a section</a>${section?`<a href="${section[0]}">${section[1]} overview</a>`:''}`}</div><p class="caption">A project in development. Design studies and calculated estimates are identified throughout.</p></footer></body></html>`;}
let pages=[];const systemStudyLinks=new Map();
async function write(url,title,body){
  const systemMatch=url.match(/^\/systems\/([^/]+)\//);
  if(systemMatch){
    const prefix='/systems/'+systemMatch[1]+'/';
    body=keepLocal(body,prefix);
    body=body.replace(/<a\b[^>]*href="\/explore\/"[^>]*>[\s\S]*?<\/a>/g,'');
    for(const m of body.matchAll(/href="\/systems\/([^/]+)\/studies\/([^/]+)\//g)){
      if(!systemStudyLinks.has(m[1]))systemStudyLinks.set(m[1],new Set());
      systemStudyLinks.get(m[1]).add(m[2]);
    }
  }
const rel=url==='/'?'index.html':url.replace(/^\//,'')+'index.html';const file=path.join(out,rel);await mkdir(path.dirname(file),{recursive:true});await writeFile(file,layout(title,body,url));pages.push(rel);}
await write('/','Engineering at the edge of water',`<section class="hero wrap"><div class="hero-water" data-depth=".045">${flow('hero-flow')}</div><div class="hero-copy" data-depth=".012">${eyebrow('WAHOO RACING / DEVELOPMENT JOURNAL')}<h1>Engineering<br>at the edge<br>of water.</h1><p class="lead">Inside the development of a jetboard.<br>The geometry. The decisions. The evidence.</p><div class="actions">${link('/explore/','Explore the board','button')}${link('/history/','Read the history')}</div></div><div class="hero-object" data-depth=".12">${img('hull-hero.webp','Current H0 R03 hull, rendered from the actual geometry','',true)}</div><p class="hero-label"><strong>H0 / R03</strong>Actual hull geometry<br><span>Illustrative studio finish</span></p></section><section class="section wrap"><div class="section-heading">${eyebrow('CHOOSE YOUR ROUTE')}<h2>Six ways into Wahoo.</h2><p>Choose a section here. Inside it, follow its own story and return Home whenever you want a different route.</p></div><div class="route-directory">${sections.map(([url,name,description],i)=>`<a href="${url}"><span class="number">0${i+1}</span><h3>${name}</h3><p>${description}</p><span aria-hidden="true">↗</span></a>`).join('')}</div></section><section class="section wrap"><div class="heading-row"><div>${eyebrow('LATEST INVESTIGATIONS')}<h2>From the workshop.</h2></div>${link('/journal/','Open the journal')}</div><div class="journal-grid">${updates.slice(0,3).map(card).join('')}</div></section>`);
await write('/systems/','Systems',pageIntro('SYSTEMS','One board.<br>Connected engineering.','Explore each system and the development records that connect it to the whole board.')+`<section class="wrap systems-index">${site.systems.map((s,i)=>`<a href="/systems/${s.slug}/"><span class="number">${String(i+1).padStart(2,'0')}</span><div><h2>${s.name}</h2><p>${s.summary}</p><small>${updates.some(u=>u.systems.includes(s.slug))?'Development records available':'System overview · detailed records to follow'}</small></div>${arrow}</a>`).join('')}</section>`);
await write('/explore/','The board',pageIntro('THE BOARD / H0 R03','Get closer to the geometry.','Switch between the current hull views and the earlier complete-board concept. Each is kept in its own context.')+`<section class="wrap section view-explorer"><div class="view-controls" role="group" aria-label="Choose board view"><button type="button" data-view="hero" aria-pressed="true">Current hull</button><button type="button" data-view="bottom" aria-pressed="false">Underside</button><button type="button" data-view="archive" aria-pressed="false">Earlier concept</button></div><div class="bare-visual explorer-image">${flow('explore-flow')}<img id="explore-image" src="/assets/hull-hero.webp" alt="Current H0 R03 hull" width="1600" height="850"></div><p id="view-caption" role="status">H0 R03 · actual hull geometry, illustrative studio finish. This is the hull, not a complete assembly.</p><p class="caption">Image-based exploration. Interactive 3D and component removal will follow when the assembly assets are prepared.</p></section>`);
for(const s of site.systems){if(s.slug==='hull-hydrodynamics'){await write('/systems/'+s.slug+'/','Hull & Hydrodynamics',pageIntro('SYSTEM / 01','Shape. Balance. Behaviour.','Hull & Hydrodynamics — understanding the surface beneath the ride.')+`<section class="wrap split section"><figure class="bare-visual">${flow('hull-flow')}${img('hull-bottom.webp','Current H0 R03 underside')}<figcaption>Actual H0 R03 geometry · illustrative finish</figcaption></figure><div><h2>The real surface,<br>up close.</h2><p>The engineering geometry remains the reference. Investigate the rocker, channels and shaped stern without replacing the design with an invented model.</p>${link('/explore/','Inspect the hull views')}</div></section>${hullGraphics()}${geometryFeature()}${engineeringFeature()}<section class="wrap section"><h2>How load changes immersion.</h2><p class="lead">A level hull settles deeper as the requested mass increases.</p><div class="chart-layout">${chart()}<aside><h3>What this does not show</h3><p>Sealed external envelope. Pitch = roll = 0. Openings, intake and seals are not modelled.</p><p>No dynamic-performance, physical-test or safe-payload claim.</p>${link('/journal/level-attitude-displacement/','Read the study')}</aside></div></section><section class="wrap section"><h2>Behind the numbers.</h2><div class="journal-grid">${updates.filter(u=>u.systems.includes(s.slug)&&u.type!=='Archive').map(card).join('')}</div></section><section class="wrap section">${link('/systems/','Back to all systems')}</section>`);}else{const records=updates.filter(u=>u.systems.includes(s.slug));await write('/systems/'+s.slug+'/',s.name,pageIntro('SYSTEM / DEVELOPMENT',s.name,s.summary)+systemVisuals(s.slug)+`<section class="wrap section prose"><h2>${records.length?'The brief, the decisions, the evidence.':'Documentation is taking shape.'}</h2><p>${records.length?'Explore requirements, proposed concepts and earlier design material. Each record identifies its source and what remains unverified.':'This system belongs to the development programme. A reviewed technical article has not yet been published here.'}</p><p>Future updates will retain the question investigated, the decisions made, supporting sources, limitations and next steps.</p>${records.map(u=>`<p>${link('/journal/'+u.slug+'/',u.title)}</p>`).join('')}${link('/systems/','Back to all systems')}</section>`);}}
await write('/journal/','Development journal',pageIntro('DEVELOPMENT / JOURNAL','The work, in the open.','Design records, investigations and calculated results. Every update retains its sources and limitations.')+`<section class="wrap section reading-paths"><h2>Choose a reading path.</h2><p>Follow a subject in order, or use the filters below to find a particular investigation.</p>${readingGroups.map(([name,slugs],i)=>`<details id="${groupId(i)}"><summary>${name} · ${slugs.length} records</summary><ol>${slugs.map(slug=>updates.find(u=>u.slug===slug)).filter(Boolean).map(u=>`<li>${link('/journal/'+u.slug+'/',u.title)}</li>`).join('')}</ol></details>`).join('')}</section><section class="wrap section"><h2>All investigations</h2><div class="journal-filters"><label>System <select id="filter-system"><option value="all">All systems</option>${site.systems.map(s=>`<option value="${s.slug}">${s.name}</option>`).join('')}</select></label><label>Update type <select id="filter-type"><option value="all">All types</option>${[...new Set(updates.map(u=>u.type))].map(t=>`<option>${t}</option>`).join('')}</select></label><p id="filter-count" role="status">${updates.length} records</p></div><div class="journal-grid" id="journal-records">${updates.map(card).join('')}</div><p id="journal-empty" hidden>No published records match these filters. Try another system or update type.</p></section>`);
function articleBody(u,context=null){const prefix=context?'/systems/'+context.slug+'/studies/':'/journal/';const group=readingGroups.find(([,slugs])=>slugs.includes(u.slug));const sequence=context?readingSequence(updates).filter(r=>r.systems.includes(context.slug)):group[1].map(slug=>updates.find(r=>r.slug===slug)).filter(Boolean);const index=sequence.findIndex(r=>r.slug===u.slug);const next=index>=0?sequence[index+1]:null;const previous=index>0?sequence[index-1]:null;return `<article class="article wrap"><header class="article-heading">${link(context?'/systems/'+context.slug+'/':'/journal/',context?context.name+' overview':'Development journal')}${eyebrow(u.revision+' / '+u.evidence)}<h1>${u.title}</h1><p class="lead">${u.summary}</p><p class="meta">${u.dateLabel}</p></header>${u.hero?`<figure class="article-hero bare-visual">${img(u.hero,u.heroAlt??(u.type==='Archive'?'Earlier design render, archive date unconfirmed':'Actual H0 R03 hull underside'))}<figcaption>${u.heroCaption??(u.type==='Archive'?'Earlier design render · not the current assembly':'Actual H0 R03 geometry · illustrative finish')}</figcaption></figure>`:''}<div class="article-body">${u.sections.map((s,i)=>`<section><h2>${s.title}</h2><p>${s.text}</p>${s.visual?(geometryVisual(s.visual)||engineeringVisual(s.visual)||developmentVisual(s.visual)):''}${u.chart&&i===1?chart():''}</section>`).join('')}${u.gallery?`<section class="article-gallery"><h2>${u.galleryTitle??'From the archive'}</h2>${u.gallery.map(g=>`<figure><a href="/assets/${g.image}" aria-label="Open full-size image">${img(g.image,g.caption,g.class??'')}</a><figcaption>${g.caption}</figcaption></figure>`).join('')}</section>`:''}${u.downloads?`<section class="source-drawings"><h2>Inspect the original drawings</h2><p>Open the complete archived sheets for annotations and study context.</p>${u.downloads.map(d=>`<a class="text-link" href="/assets/${esc(d.file)}">${esc(d.label)} ↗</a>`).join('')}</section>`:''}<section class="source-notes"><h2>Source record</h2><ul>${u.sources.map(s=>`<li>${esc(s)}</li>`).join('')}</ul><p>${u.changes}</p><p>Later corrections and follow-up studies will link back to this record.</p></section><nav class="reading-next" aria-label="Study reading order">${eyebrow(context?context.name:group[0])}${previous?link(prefix+previous.slug+'/','Previous: '+previous.title):''}${next?link(prefix+next.slug+'/','Next: '+next.title):`<p>You have reached the end of this reading path.</p>`}${link(context?'/systems/'+context.slug+'/':'/journal/#'+groupId(readingGroups.indexOf(group)),context?'Return to '+context.name:'Return to this reading path')}</nav></div></article>`;}
for(const u of updates)await write('/journal/'+u.slug+'/',u.title,articleBody(u));
// Resolve only studies reached from a system, including their follow-up links.
for(const system of site.systems){const done=new Set();const needed=systemStudyLinks.get(system.slug)??new Set();for(const slug of needed){if(done.has(slug))continue;const record=updates.find(u=>u.slug===slug);if(!record)throw Error('Unknown study '+slug);done.add(slug);await write('/systems/'+system.slug+'/studies/'+slug+'/',record.title,articleBody(record,system));}}

await write('/history/','Development history',pageIntro('DEVELOPMENT / HISTORY','Progress has a memory.','From the early board concept to the current hull and its first completed flow simulation. This is the sequence of the work; dates are shown only where confirmed.')+withoutSectionLinks(archiveSpread())+`<section class="wrap section"><figure>${img('archive-sketch.webp','Original board layout sketch','sketch')}<figcaption>Original sketch · date unconfirmed · contrast-adjusted for display</figcaption></figure></section><section class="wrap section history-timeline">${[
['EARLIER CONCEPTS / DATE UNCONFIRMED','The board before H0','Complete-board renders, layout sketches and rider-control concepts established an earlier design direction. These are archive concepts, not the current assembly.'],
['H0 / R01','Establish a common reference','Coordinate and reference-verification work established how the hull would be measured and compared.'],
['H0 / R02','Read the surface','Sections, longitudinal arc-length paths, curvature, tail geometry and feature checks made the hull geometry inspectable. These are geometric investigations, not performance tests.'],
['H0 / R03','Investigate flotation and balance','Sealed-envelope hydrostatics and mass-position studies examined displacement and equilibrium assumptions. They do not establish a safe payload or dynamic performance.'],
['NUMERICAL COMMISSIONING / EARLIER CHECKPOINT','Start the corrected flow run','The initial 20 km/h record captured the run at an earlier 0.95-second checkpoint. It remains an earlier observation of the same investigation.'],
['NUMERICAL COMMISSIONING / COMPLETED RUN','Complete the 20 km/h analysis','The corrected fixed-hull run reached 1.57998 seconds with 24,342 force samples. Additional saved fields and graphs extended the record. Vertical force remains window-dependent; completion does not establish validated performance.']
].map(([tag,title,text])=>`<article>${eyebrow(tag)}<h2>${title}</h2><p>${text}</p></article>`).join('')}</section>`);
await write('/roadmap/','Roadmap',pageIntro('DEVELOPMENT / ROADMAP','The next questions matter.','An evidence-led plan, without invented completion percentages or launch dates.')+`<section class="wrap section roadmap">${[['Documented','Reference & geometric studies','R01 reference-verification and R02 surface-investigation records are available.','/history/'],['Calculated','Dry mass & hydrostatics','R03 numerical hydrostatics provide a basis for investigating flotation and balance. They are not an operational rating.','/journal/level-attitude-displacement/'],['Design brief','Propulsion & service architecture','Review the V1 requirements, matched sourcing, packaging and the path from bench work to water testing.','/journal/from-brief-to-test/'],['Next inputs','Loaded equilibrium','Confirm fuel properties and rider mass, stance and centre of gravity before interpreting loaded cases.',null],['Completed run','20 km/h numerical commissioning','The corrected fixed-hull run completed at 1.57998 seconds with 24,342 force samples and four later saved field checkpoints. Vertical force remains window-dependent.','/journal/20kmh-completed-analysis/'],['Evidence needed','Hydrodynamic performance','A commissioned solver is not a validated result. Publish performance conclusions only with reviewed methods, validation and limitations.',null],['Evidence needed','Physical testing','Record test setup, conditions, measurements and revisions when verified physical-test evidence becomes available.',null]].map(([tag,title,text,url])=>`<article>${eyebrow(tag)}<div><h2>${title}</h2><p>${text}</p></div></article>`).join('')}</section>`);
await write('/back/','Back Wahoo',pageIntro('BACK WAHOO','Build the next<br>chapter with us.','A place for investment conversations, technical expertise and a community following the work.')+`<section class="wrap section support-sections">${[['investors','Invest in the vision.','Investor conversations','The development record will form the basis for discussions about the project, its engineering needs and next milestones. No investment offering or subscription is open on this site.'],['partners','Bring your expertise.','Technical partnerships','Materials, manufacturing, propulsion, controls and testing all connect to the board. Tell us which field you work in and how you would like to contribute.'],['community','Follow the work.','Community & future crowdfunding','Get in touch to express interest in future project updates. A crowdfunding campaign has not been announced, and the site does not collect donations or payments.']].map(([id,title,tag,text])=>`<article id="${id}">${eyebrow(tag)}<h2>${title}</h2><p>${text}</p>${site.contactEmail?link('mailto:'+esc(site.contactEmail)+'?subject='+encodeURIComponent('Wahoo — '+tag),'Contact us about '+tag.toLowerCase(),'button'):''}</article>`).join('')}<p class="contact-status">${site.contactEmail?`Email ${link('mailto:'+esc(site.contactEmail),esc(site.contactEmail))}. The buttons open your email application.`:'A public contact channel has not yet been confirmed.'}</p></section>`);
await write('/inspect/','Inspect an engineering drawing',pageIntro('ENGINEERING / DRAWING VIEWER','Inspect the detail.','Use the size control to inspect the original-resolution drawing. On smaller screens, scroll within the drawing after zooming.')+`<section class="wrap section"><div class="actions"><button class="button" type="button" data-image-zoom disabled>Original size</button><a class="text-link" data-image-return href="/">Return to Home ↗</a></div><p data-image-status role="status">Choose a drawing from an engineering article.</p><div class="image-viewport" tabindex="0" aria-label="Drawing viewport"><img data-inspection-image hidden alt="Engineering drawing selected from the development journal"></div></section>`);
await write('/404/','Page not found',pageIntro('404','This page is not here.','The development record is still growing.')+`<section class="wrap section">${link('/','Return home')}${link('/journal/','Browse the journal')}</section>`);
// Cloudflare Pages needs a root 404.html to disable its SPA fallback.
await writeFile(path.join(out,'404.html'),await readFile(path.join(out,'404/index.html'),'utf8'));
await writeFile(path.join(out,'assets/displacement.json'),JSON.stringify(points));
await writeFile(path.join(out,'build-manifest.json'),JSON.stringify(pages));
console.log(`Built ${pages.length} pages and ${updates.length} published records. ${allUpdates.length-updates.length} draft excluded.`);
