const plots={
 'study-cg-sweep':['cg-trim-sensitivity.svg','Static trim sensitivity to hypothetical longitudinal CG','Case A dry mass held fixed; roll constrained to zero. Numerical sensitivity, not packaging approval.'],
 'study-curvature':['centreline-curvature.svg','Original hull centreline signed curvature versus arc length','Corrected arc-length samples at 0.125 mm spacing. CAD-derived planar curvature, not a measured flow result.'],
 'study-free-surface':['cfd-freeSurface.png','Saved water interface at 0.95 s, elevation in metres','Actual alpha.water = 0.5 surface · fixed hull · top projection · colour range −0.10 to +0.10 m.'],
 'study-velocity':['cfd-centerPlane.png','Centre-plane velocity at 0.95 seconds','Y = 0 slice · air and water included · 0–8 m/s colour range · commissioning result.'],
 'study-wake':['cfd-nearWake.png','Transverse wake-plane velocity at 0.95 seconds','X = −0.25 m · air and water included · 0–8 m/s · no smoothing or invented wake geometry.'],
 'study-forces':['cfd-force-windows.svg','Time-weighted drag, vertical force and pitch moment window means','Original 0.05 s window means · horizontal bars are time intervals, not error bounds. Vertical force is not converged.'],
 'study-mass':['dry-mass.svg','Calculated dry-board masses for source cases A, B and C','R03 dry mass scenarios · excludes fuel and rider · estimated component masses, not measured board weights.']
};
export function engineeringVisual(name){const p=plots[name];if(!p)return '';return `<figure class="engineering-visual study-plot"><a href="/assets/engineering/${p[0]}" aria-label="Open full-size graphic: ${p[1]}"><img src="/assets/engineering/${p[0]}" alt="${p[1]}" loading="lazy" decoding="async"></a><figcaption>${p[2]} Click the graphic to inspect at full size.</figcaption></figure>`;}
export function engineeringFeature(){return `<section class="section wrap engineering-evidence"><div class="heading-row"><div><p class="eyebrow">COMPUTED FLOW / H0-CFD-001</p><h2>The engineering,<br>made visible.</h2></div><a class="text-link" href="/journal/first-corrected-cfd-run/">Inspect the simulation <span aria-hidden="true">↗</span></a></div><p class="lead">From the actual hull surface to pressure, flow and force histories. Explore what the studies show, how they were checked and what comes next.</p><figure><a href="/journal/first-corrected-cfd-run/"><img src="/assets/engineering/cfd-hullPressure.png" alt="Computed total pressure on the original hull, underside projection" loading="lazy" decoding="async"></a><figcaption>20 km/h boundary-speed target · 0.95 s saved checkpoint · fixed hull. Pressure includes hydrostatic contribution. CFD commissioning, not final performance validation.</figcaption></figure><div class="evidence-links">${[['reading-the-hull-surface','01 / GEOMETRY','Read the surface','Sections, curvature checks and feature intent.'],['mass-and-centre-of-gravity','02 / MASS','Account for every kilogram','Construction scenarios and component positions.'],['dry-board-flotation-and-trim','03 / EQUILIBRIUM','Understand the attitude','Dry flotation and calculated static trim.']].map(([slug,tag,title,body])=>`<a href="/journal/${slug}/"><small>${tag}</small><h3>${title}</h3><p>${body}</p><span>Open study ↗</span></a>`).join('')}</div></section>`;}
