const plots={
 'study-cg-sweep':['cg-trim-sensitivity.svg','Static trim sensitivity to hypothetical longitudinal CG','Case A dry mass held fixed; roll constrained to zero. Numerical sensitivity, not packaging approval.'],
 'study-curvature':['centreline-curvature.svg','Original hull centreline signed curvature versus arc length','Corrected arc-length samples at 0.125 mm spacing. CAD-derived planar curvature, not a measured flow result.'],
 'study-free-surface':['cfd-freeSurface.png','Saved water interface at 0.95 s, elevation in metres','Actual alpha.water = 0.5 surface · fixed hull · top projection · colour range −0.10 to +0.10 m.'],
 'study-velocity':['cfd-centerPlane.png','Centre-plane velocity at 0.95 seconds','Y = 0 slice · air and water included · 0–8 m/s colour range · commissioning result.'],
 'study-wake':['cfd-nearWake.png','Transverse wake-plane velocity at 0.95 seconds','X = −0.25 m · air and water included · 0–8 m/s · no smoothing or invented wake geometry.'],
 'study-forces':['cfd-force-windows.svg','Time-weighted drag, vertical force and pitch moment window means','Original 0.05 s window means · horizontal bars are time intervals, not error bounds. Vertical force is not converged.'],
 'study-mass':['dry-mass.svg','Calculated dry-board masses for source cases A, B and C','R03 dry mass scenarios · excludes fuel and rider · estimated component masses, not measured board weights.']
};
const cfFigure=(file,caption)=>`<figure class="engineering-visual study-plot"><a href="/assets/engineering/${file}" aria-label="Open completed-run graphic"><img src="/assets/engineering/${file}" alt="${caption}" loading="lazy" decoding="async"></a><figcaption>${caption} Open for full-size inspection.</figcaption></figure>`;
const completed={
 'cfd20-history':['cfd20-force-history.png','Complete force history through 1.579983709 s. Dashed line: continuation from 0.95 s.'],
 'cfd20-means':['cfd20-nested-means.svg','Time-weighted means in nested windows, all ending at 1.579983709 s.'],
 'cfd20-surface':['cfd20-freeSurface-1-579983709.png','Final saved water interface. Elevation from −0.10 to +0.10 m; fixed-hull transient flow.']
};
export function engineeringVisual(name){
 if(completed[name])return cfFigure(...completed[name]);
 if(name==='cfd20-sequence')return ['1-2','1-35','1-5'].map(t=>cfFigure('cfd20-freeSurface-'+t+'.png','Saved water interface at '+t.replace('-','.')+' s; common elevation scale and projection.')).join('');
 if(name==='cfd20-planes')return [['centerPlane','Centre-plane velocity at Y = 0'],['waterline','Waterline-plane velocity at Z = −0.01 m'],['nearWake','Wake-plane velocity at X = −0.25 m']].map(([f,c])=>cfFigure('cfd20-'+f+'-1-579983709.png',c+'; final checkpoint, 0–8 m/s, both phases included.')).join('');
const p=plots[name];if(!p)return '';return `<figure class="engineering-visual study-plot"><a href="/assets/engineering/${p[0]}" aria-label="Open full-size graphic: ${p[1]}"><img src="/assets/engineering/${p[0]}" alt="${p[1]}" loading="lazy" decoding="async"></a><figcaption>${p[2]} Click the graphic to inspect at full size.</figcaption></figure>`;}
export function engineeringFeature(){return `<section class="section wrap engineering-evidence"><div class="heading-row"><div><p class="eyebrow">COMPUTED FLOW / H0-CFD-001</p><h2>20 km/h.<br>The completed run.</h2></div><a class="text-link" href="/journal/20kmh-completed-analysis/">Inspect the simulation <span aria-hidden="true">↗</span></a></div><p class="lead">24,342 force samples. Four later flow checkpoints. Explore the completed fixed-hull commissioning run, its provisional force averages and the next validation questions.</p><figure><a href="/journal/20kmh-completed-analysis/"><img src="/assets/engineering/cfd20-hullPressure-1-579983709.png" alt="Computed total pressure on the original hull, underside projection" loading="lazy" decoding="async"></a><figcaption>20 km/h boundary-speed target · 1.57998 s final checkpoint · fixed hull. Pressure includes hydrostatic contribution. CFD commissioning, not final performance validation.</figcaption></figure><div class="evidence-links">${[['reading-the-hull-surface','01 / GEOMETRY','Read the surface','Sections, curvature checks and feature intent.'],['mass-and-centre-of-gravity','02 / MASS','Account for every kilogram','Construction scenarios and component positions.'],['dry-board-flotation-and-trim','03 / EQUILIBRIUM','Understand the attitude','Dry flotation and calculated static trim.']].map(([slug,tag,title,body])=>`<a href="/journal/${slug}/"><small>${tag}</small><h3>${title}</h3><p>${body}</p><span>Open study ↗</span></a>`).join('')}</div></section>`;}
