const plots={
 'reference-side':['reference-side.png','Reference coordinates in side projection','Native surface samples in the R01 frame, with recorded reference points. A sampled projection, not a reconstructed hull.'],
 'reference-end':['reference-end.png','Reference coordinates in end projection','Looking across the recorded Y/Z coordinates. Markers include points at different longitudinal positions.'],
 'arc-convergence':['arc-convergence.svg','Six converged curvature-rate features across four sample intervals','Each series is relative to its own finest-grid magnitude. Zero at 0.125 mm is the comparison baseline, not zero error.'],
 'converged-map':['converged-map.png','Locations of six converged section features','Positions on sampled R02 geometry. Convergence establishes numerical repeatability, not a defect or a performance result.'],
 'tail-rocker':['tail-rocker.svg','Lower-envelope longitudinal profiles through the tail','Original tail-study samples; R01 longitudinal coordinates. Separate source branches remain separate.'],
 'sampled-symmetry':['sampled-symmetry.svg','Maximum sampled mirrored deviation by hull station','Logarithmic vertical scale. Discrete geometric comparison, not continuous-surface certification.']
};
const figure=(file,alt,caption)=>`<figure class="engineering-visual study-plot"><a href="/assets/geometry/${file}" aria-label="Open full-size graphic: ${alt}"><img src="/assets/geometry/${file}" alt="${alt}" loading="lazy" decoding="async"></a><figcaption>${caption} Open the graphic for full-size inspection.</figcaption></figure>`;
export function geometryVisual(name){
 if(plots[name])return figure(...plots[name]);
 if(name==='arc-library')return `<div class="arc-library">${['S90','S75','S50','S25','P25','P50','P75','P90'].map(code=>`<details><summary>${code[0]==='S'?'Starboard':'Port'} ${code.slice(1)}% half-beam — open the three-part analysis</summary>${figure('arc-'+code+'.png',code+' arc-length height, curvature and curvature-rate study','Four nested intervals: 1, 0.5, 0.25 and 0.125 mm. Curvature and rate use signed logarithmic scales; gaps retain the source derivative mask.')}<a class="text-link" href="/assets/geometry/source-arc-${code}.png">Open original annotated study sheet ↗</a></details>`).join('')}</div>`;
 return '';
}
export function geometryFeature(){return `<section class="section wrap geometry-feature"><p class="eyebrow">GEOMETRY / INSIDE THE ANALYSIS</p><h2>More than a beautiful surface.</h2><p class="lead">Reference points. Nine longitudinal paths. Four sampling intervals. Explore the drawings and numerical checks behind the hull.</p>${figure('feature-map.png','Nine feature-review regions on the sampled hull','R02 geometric review. Amber marks R5 and R9, where intent remains unresolved.')}<div class="evidence-links">${[['reference-system','01 / REFERENCE','Start with the coordinates'],['arc-length-analysis','02 / CURVATURE','Follow all nine paths'],['geometry-conversion-validation','03 / VERIFICATION','Check the analysis geometry'],['tail-section-investigation','04 / TAIL','Read the tail sections'],['hull-feature-review','05 / FEATURE INTENT','Investigate each region'],['20kmh-completed-analysis','06 / FLOW','Continue into simulation']].map(([slug,tag,title])=>`<a href="/journal/${slug}/"><small>${tag}</small><h3>${title}</h3><span>Explore the study ↗</span></a>`).join('')}</div></section>`;}
