const photo=(name,alt,caption='',hero=false)=>`<figure class="story-photo"><img src="/assets/history/${name}-1920.webp" srcset="/assets/history/${name}-800.webp 800w, /assets/history/${name}-1920.webp 1920w" sizes="${hero?'100vw':'(max-width: 760px) 100vw, 70vw'}" width="1920" height="1280" alt="${alt}" ${hero?'fetchpriority="high"':'loading="lazy"'} decoding="async">${caption?`<figcaption>${caption}</figcaption>`:''}</figure>`;
const label=(n,t)=>`<p class="story-label"><span>${n}</span> ${t}</p>`;
export function historyStory(record){return `<div class="history-story">
<section class="story-hero">
${photo('water','A helmeted rider drives a jetboard through a sweeping turn','',true)}
<div class="story-hero-copy"><p class="story-label">WAHOO / OUR HISTORY</p><h1>Before the drawings,<br>there was the water.</h1><p>A rider’s experience. A workshop’s questions.<br>A bigger ambition for jetboarding.</p><a href="#origin" class="story-scroll">Explore the story <span aria-hidden="true">↓</span></a></div>
</section>
<section id="origin" class="wrap story-intro">
${label('01','THE STARTING POINT')}<h2>An extraordinary ride.<br>A reason to rethink it.</h2>
<div class="story-prose"><p class="story-lead">Wahoo began with the experience of riding, racing and working on jetboards—and the belief that more people should be able to enjoy them.</p><p>For Max, the perspective came from both sides of the product: as a rider and racer, and as a former dealer. The excitement on the water was clear. So were the questions that followed it back to shore.</p><p>What does it cost to own? How easily can it be maintained? Who helps when something goes wrong? Those questions became part of the design brief.</p></div>
</section>
<section class="wrap story-pair">${photo('carve','A rider carving across the water','The experience that started the questions.')}<div class="story-side">${label('02','BEYOND THE RIDE')}<h2>A great product needs<br>a business behind it.</h2><p>From Max’s perspective, the category needed more attention to the complete ownership experience: affordability, serviceability, reliable support and a commercially sustainable product.</p><p>Performance creates the first impression. What happens after the sale determines whether people stay with the sport.</p><p class="story-emphasis">The ambition is to build a better board—and a better proposition for the person who owns it.</p></div></section>
<section class="story-wide">${photo('team','Three people work together on an open jetboard beside the water','Earlier riding and workshop experience · existing boards, before the current Wahoo design.')}</section>
<section class="wrap story-intro story-workshop">${label('03','BACK ON THE BENCH')}<h2>Every ride came<br>back to the workshop.</h2><div class="story-prose"><p class="story-lead">The learning was hands-on: engines opened, components inspected, exhausts made and ideas taken back to the water.</p><p>Working inside a compact board makes the trade-offs tangible. The engine, fuel, cooling, controls and access for maintenance all compete for space. A change to one part affects the whole.</p><p>This earlier work helped shape Wahoo’s approach: think about the system, the rider and the person who will have to service it.</p></div></section>
<div class="wrap story-workshop-grid">${photo('exhaust','Hands fitting a fabricated expansion chamber above an open engine compartment','Fabrication and packaging · making the parts work together.')}${photo('pistons','Three used pistons arranged on a carbon-fibre board','Components from earlier workshop work.')}${photo('engine','An open jetboard showing the engine, fuel tank, hoses and wiring','Inside the board · a tightly connected system.')}</div>
<section class="wrap story-intro">${label('04','YOU OWN IT')}<h2>The freedom should continue<br>back on shore.</h2><div class="story-prose"><p class="story-lead">An owner should be able to understand the machine they ride.</p><p>That conviction grew out of the workshop. Wahoo’s design priorities include access to components, understandable diagnostics, clear manuals and a practical route to replacement parts. These are goals for the product being developed—and part of what prototypes must help us prove.</p><p>For riders who enjoy the mechanical side, looking after a board can be part of the pleasure. For everyone else, maintenance should be straightforward to arrange, with clear information and support. Ownership should give people confidence.</p></div></section>
<section class="wrap story-pair">${photo('racing','Riders wearing numbered bibs at an earlier jetboard racing event','Earlier racing experience · before the current Wahoo development programme.')}<div class="story-side">${label('05','A PLACE ON THE START LINE')}<h2>From the first ride<br>to a bigger possibility.</h2><p>Max recalls taking part in JetSurf world championship events as a nonprofessional rider, sharing the experience with international competitors. That personal path—from enjoying the board to entering a race—helped shape what he wants Wahoo to make possible.</p><p>The ambition is a welcoming community where riders can learn, share knowledge and choose their own level of involvement. Some will stay with leisure riding. Others may want to explore competition.</p><p class="story-emphasis">A board to enjoy today. A sport to grow into.</p><p>Wahoo’s own community and event programme are ambitions for the future.</p></div></section>
<section class="wrap story-pair story-reverse"><div class="story-side">${label('06','AN IDENTITY TAKES SHAPE')}<h2>Fast by nature.<br>Purposeful by design.</h2><p>The wahoo—a fast, streamlined open-water fish—gave the project its name and a direction: lean form, purposeful movement and no unnecessary complexity.</p><p>Earlier board concepts, graphics and layout studies explored that identity. They belong to the story of how Wahoo developed; they are distinct from today’s H0 hull.</p></div>${photo('concepts','Three earlier board livery concepts in black, red and white','Earlier visual concepts · not the current H0 assembly.')}</section>
<section class="story-wide story-water-break">${photo('wake','An overhead view of a jetboard tracing a curved white wake across green water')}<div class="story-water-copy"><p class="story-label">THE AMBITION</p><h2>Keep the excitement.<br>Rethink the ownership.</h2></div></section>
<section class="wrap story-intro">${label('07','THE CHAPTER WE ARE BUILDING')}<h2>Race first.<br>A wider horizon.</h2><div class="story-prose"><p class="story-lead">The plan starts with a demanding race platform, then carries what is learned into a more accessible leisure board.</p><p>That means considering the future cost of materials, manufacturing and servicing alongside the engineering—not leaving them until the end. Race-specific choices can evolve for leisure use while preserving the thinking behind the architecture.</p><p>AI now helps accelerate research, explore options and organise the development record. Engineering judgement, specialist input, physical prototypes and measured testing still have to turn those ideas into a dependable product.</p><p>Wahoo is in development. The ambition is clear; proving it remains the work ahead.</p></div></section>
<section class="wrap story-record"><div class="story-record-heading">${label('08','THE DEVELOPMENT RECORD')}<h2>Ideas become evidence.</h2><p>The sketches, geometry studies and numerical investigations behind the current chapter. Dates are shown only where confirmed.</p></div><details><summary>Explore the design archive and engineering milestones <span aria-hidden="true">＋</span></summary>${record}</details></section>
<section class="wrap story-ending">${photo('launch','A rider carrying a board out of the water in warm evening light')}<div><p class="story-label">STILL WRITING THE STORY</p><h2>More time<br>on the water.</h2><p>That is the experience worth building for.</p></div></section>
</div>`;}
