import {landingStory} from './landing-story.mjs';
import {systemIcon} from './system-icons.mjs';
// Claude Design composition, rendered by the existing static content pipeline.
export function brand(tone='white',word=false){return `<img src="/assets/brand/wahoo-${word?'name-':''}${tone}.png" alt="Wahoo" width="${word?2798:1732}" height="${word?400:2798}">`;}
export function home({site,updates,sections,img,link,card,chart,flow,sectionFigures}){return `
<section class="brand-opening ownership-opening" aria-label="Wahoo Racing"><div class="brand-stage"><div class="brand-frame"><span class="brand-glow" aria-hidden="true"></span><img src="/assets/brand/wahoo-symbol-white.png" alt="Wahoo" width="1303" height="1958"></div><p class="ownership-statement"><span>You</span><span>Own</span><span>It<span class="ownership-period">.</span></span></p></div><a class="brand-scroll" href="#intro" aria-label="Scroll to start">Scroll<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M12 5v14M6 13l6 6 6-6"/></svg></a></section>
${landingStory}

<section class="section board-panel" id="board"><div class="wrap"><p class="eyebrow">01 / THE BOARD</p><div class="heading-row"><h2>Eleven systems.<br>Every detail<br>has a reason.</h2><p class="lead">From hull to handlebar, each system has its own page, with its open questions and the evidence behind it.</p></div><div class="home-systems">${site.systems.map((s,i)=>`<div><div class="system-symbol">${systemIcon(i)}<span class="number">${String(i+1).padStart(2,'0')}</span></div><h3>${s.name}</h3><p>${s.summary}</p></div>`).join('')}<a class="systems-entry" href="/explore/"><span aria-hidden="true">↗</span><strong>Explore the<br>whole board</strong></a></div></div></section>
<section class="section wrap home-evidence"><p class="eyebrow">02 / EVIDENCE</p><div class="heading-row"><h2>Cut it open.<br>Float it.</h2><p class="lead">Real geometry and source calculations. Explore the complete studies for methods, assumptions and limitations.</p></div><div class="split"><div class="station-explorer"><h3>Transverse sections</h3><p class="caption">H0 R02 · actual sampled coordinates, equal axis scale.</p><div class="view-controls" role="group" aria-label="Hull section station">${sectionFigures.map(({station})=>`<button type="button" data-station="${station}" aria-pressed="${station===50}">${station}%</button>`).join('')}</div>${sectionFigures.map(({station,svg})=>`<figure data-station-figure="${station}" ${station===50?'':'hidden'}>${svg}</figure>`).join('')}<p class="caption">0% = stern, 100% = bow. All valid source branches retained. Geometric study, not a performance test.</p>${link('/systems/hull-hydrodynamics/','Open hull & hydrodynamics')}</div>${chart()}</div></section>
<section class="section wrap"><p class="eyebrow">03 / THE STORY</p><div class="heading-row"><h2>From sketch<br>to surface.</h2><p class="lead">Keep the earlier ideas in view. Each stage carries its own questions and its own evidence.</p></div><div class="story-pair"><figure>${img('archive-sketch.webp','Original board layout sketch')}<figcaption>Earlier concept · date unconfirmed.</figcaption></figure><figure>${img('hull-hero.webp','Current hull geometry')}<figcaption>H0 R03 · the current hull reference.</figcaption></figure></div>${link('/history/','Follow the development history')}</section>
<section class="section wrap"><div class="heading-row"><div><p class="eyebrow">04 / THE JOURNAL</p><h2>The work,<br>in the open.</h2></div>${link('/journal/','All '+updates.length+' investigations')}</div></section>

<section class="home-support"><div class="wrap section"><p class="eyebrow">05 / BACK WAHOO</p><h2>Build the next<br><em>chapter with us.</em></h2><div class="support-routes">${[['investors','Investment conversations'],['partners','Technical partnerships'],['community','Follow the work']].map(([id,title])=>`<a href="/back/#${id}">${title}<span>↗</span></a>`).join('')}</div><p>No investment offering, crowdfunding campaign or payment collection is open on this site.</p></div></section>`;}
