import {systemIcon} from './system-icons.mjs';
// Claude Design composition, rendered by the existing static content pipeline.
export function brand(tone='white',word=false){return `<img src="/assets/brand/wahoo-${word?'name-':''}${tone}.png" alt="Wahoo" width="${word?2798:1732}" height="${word?400:2798}">`;}
export function home({site,updates,sections,img,link,card,chart,flow,sectionFigures}){return `
<section class="brand-opening" aria-label="Wahoo Racing"><div class="brand-axis" aria-hidden="true"></div>${brand('black')}<p>Jetboard development journal</p><a href="#intro">Discover the project ↓</a></section>
<section class="hero wrap" id="intro"><div class="hero-water" data-depth=".045">${flow('hero-flow')}</div><div class="hero-copy" data-depth=".012"><p class="eyebrow">JETBOARD · IN DEVELOPMENT / H0 R03</p><h1>Engineering<br>at the edge<br><em>of water.</em></h1><p class="lead">Inside the development of a jetboard.<br>The geometry. The decisions. The evidence.</p><div class="actions">${link('/explore/','Explore the board','button')}${link('/history/','Read the history')}</div></div><figure class="hero-object" data-depth=".12">${img('hull-hero.webp','Current H0 R03 hull, rendered from the actual geometry','',true)}<figcaption>FIG. 01 / ACTUAL HULL GEOMETRY · ILLUSTRATIVE STUDIO FINISH</figcaption></figure></section>

<section class="section board-panel" id="board"><div class="wrap"><p class="eyebrow">01 / THE BOARD</p><div class="heading-row"><h2>Eleven systems.<br>Every detail<br>has a reason.</h2><p class="lead">From hull to handlebar, each system has its own page, with its open questions and the evidence behind it.</p></div><div class="home-systems">${site.systems.map((s,i)=>`<div><div class="system-symbol">${systemIcon(i)}<span class="number">${String(i+1).padStart(2,'0')}</span></div><h3>${s.name}</h3><p>${s.summary}</p></div>`).join('')}<a class="systems-entry" href="/systems/"><span aria-hidden="true">↗</span><strong>Explore the<br>whole board</strong></a></div></div></section>
<section class="section wrap home-evidence"><p class="eyebrow">02 / EVIDENCE</p><div class="heading-row"><h2>Cut it open.<br>Float it.</h2><p class="lead">Real geometry and source calculations. Explore the complete studies for methods, assumptions and limitations.</p></div><div class="split"><div class="station-explorer"><h3>Transverse sections</h3><p class="caption">H0 R02 · actual sampled coordinates, equal axis scale.</p><div class="view-controls" role="group" aria-label="Hull section station">${sectionFigures.map(({station})=>`<button type="button" data-station="${station}" aria-pressed="${station===50}">${station}%</button>`).join('')}</div>${sectionFigures.map(({station,svg})=>`<figure data-station-figure="${station}" ${station===50?'':'hidden'}>${svg}</figure>`).join('')}<p class="caption">0% = stern, 100% = bow. All valid source branches retained. Geometric study, not a performance test.</p>${link('/systems/hull-hydrodynamics/','Open hull & hydrodynamics')}</div>${chart()}</div></section>
<section class="section wrap"><p class="eyebrow">03 / THE STORY</p><div class="heading-row"><h2>From sketch<br>to surface.</h2><p class="lead">Keep the earlier ideas in view. Each stage carries its own questions and its own evidence.</p></div><div class="story-pair"><figure>${img('archive-sketch.webp','Original board layout sketch')}<figcaption>Earlier concept · date unconfirmed.</figcaption></figure><figure>${img('hull-hero.webp','Current hull geometry')}<figcaption>H0 R03 · the current hull reference.</figcaption></figure></div>${link('/history/','Follow the development history')}</section>
<section class="section wrap"><div class="heading-row"><div><p class="eyebrow">04 / THE JOURNAL</p><h2>The work,<br>in the open.</h2></div>${link('/journal/','All '+updates.length+' investigations')}</div></section>
<section class="section wrap"><p class="eyebrow">CHOOSE YOUR ROUTE</p><h2>Six ways into Wahoo.</h2><div class="route-directory">${sections.map(([url,name,description],i)=>`<a href="${url}"><span class="number">0${i+1}</span><h3>${name}</h3><p>${description}</p><span aria-hidden="true">↗</span></a>`).join('')}</div></section>
<section class="home-support"><div class="wrap section"><p class="eyebrow">05 / BACK WAHOO</p><h2>Build the next<br><em>chapter with us.</em></h2><div class="support-routes">${[['investors','Investment conversations'],['partners','Technical partnerships'],['community','Follow the work']].map(([id,title])=>`<a href="/back/#${id}">${title}<span>↗</span></a>`).join('')}</div><p>No investment offering, crowdfunding campaign or payment collection is open on this site.</p></div></section>`;}
