const blue='#24b8ff',gray='#97a6b0',white='#eef3f6';
const text=(x,y,s,color=gray,size=16,anchor='start')=>`<text x="${x}" y="${y}" fill="${color}" font-size="${size}" text-anchor="${anchor}">${s}</text>`;
const line=(x,y,X,Y,color=gray,dash='')=>`<line x1="${x}" y1="${y}" x2="${X}" y2="${Y}" stroke="${color}" stroke-width="1.5" ${dash?`stroke-dasharray="${dash}"`:''}/>`;
const circle=(x,y,r,color=blue)=>`<circle cx="${x}" cy="${y}" r="${r}" fill="none" stroke="${color}" stroke-width="2"/>`;
const path=(d,color=blue)=>`<path d="${d}" fill="none" stroke="${color}" stroke-width="2"/>`;
const svg=(label,h,body)=>`<div class="diagram-scroll" tabindex="0" role="region" aria-label="${label}; scroll horizontally on small screens"><svg class="source-diagram" viewBox="0 0 680 ${h}" role="img" aria-label="${label}" xmlns="http://www.w3.org/2000/svg"><g font-family="Arial, sans-serif">${body}</g></svg></div>`;
const figure=(body,caption)=>`<figure class="engineering-visual">${body}<figcaption>${caption}</figcaption></figure>`;
const flow=(steps)=>`<ol class="functional-flow">${steps.map((s,i)=>`<li><small>${String(i+1).padStart(2,'0')}</small><strong>${s[0]}</strong><span>${s[1]}</span></li>`).join('')}</ol>`;
export function pistonSample(degrees,rpm=12000){const r=27.25,L=102,t=degrees*Math.PI/180,q=Math.sqrt(L*L-r*r*Math.sin(t)**2);return {angle:degrees,x:r*(1-Math.cos(t))+L-q,v:(r*Math.sin(t)+r*r*Math.sin(t)*Math.cos(t)/q)*2*Math.PI*rpm/60000};}
function motionChart(velocity=false){const bottom=260,top=45,left=65,right=655;const ticks=velocity?[-40,-20,0,20,40]:[0,15,30,45,60];const y=v=>bottom-(v-(velocity?-40:0))/(velocity?80:60)*(bottom-top);return svg(velocity?'Calculated piston velocity at 12000 rpm':'Calculated piston travel from TDC',325,text(left,22,velocity?'PISTON VELOCITY / m/s':'TRAVEL FROM TDC / mm',blue,14)+ticks.map(v=>line(left,y(v),right,y(v),'#2b3940')+text(52,y(v)+5,v,gray,14,'end')).join('')+[0,90,180,270,360].map(a=>text(left+a/360*(right-left),287,a,gray,14,'middle')).join('')+path(Array.from({length:361},(_,a)=>{const p=pistonSample(a);return `${a?'L':'M'}${left+a/360*(right-left)},${y(velocity?p.v:p.x)}`;}).join(' '))+text(360,318,'Crank angle after TDC / degrees',gray,14,'middle'));}
export function reviewedVisual(name){
if(name==='hull-sandwich')return figure(svg('Conceptual composite sandwich section',250,
line(30,50,310,50,blue)+line(30,65,310,65,blue)+line(30,170,310,170,blue)+line(30,185,310,185,blue)+
Array.from({length:10},(_,i)=>circle(45+i*28,118,4,gray)).join('')+
line(310,57,345,57,gray)+text(355,63,'Outer fibre + epoxy skin',white,18)+
line(310,118,345,118,gray)+text(355,124,'Structural foam core',white,18)+
line(310,177,345,177,gray)+text(355,183,'Inner fibre + epoxy skin',white,18)),
'Conceptual section, not to scale. Skin separation and bonding are central to the sandwich concept. No core grade, thickness, fibre orientation or approved ply schedule is specified.');
if(name==='hull-mass-ranges'||name==='hull-cost-ranges'){
const cost=name==='hull-cost-ranges',max=cost?1500:10,rows=cost?[['Carbon',850,1400,1100],['Fiberglass',600,1050,800],['Glass + local carbon',700,1150,null]]:[['Carbon',5,6.5,5.5],['Fiberglass',7,9,8],['Glass + local carbon',6.5,8,null]];
const X=n=>225+n/max*400;return figure(svg(cost?'Preliminary hull manufacturing allowances':'Preliminary finished hull mass allowances',315,
text(225,25,cost?'MANUFACTURING ALLOWANCE / US$':'FINISHED HULL / kg',blue,14)+rows.map(([label,lo,hi,point],i)=>{const y=80+i*75;return text(25,y+5,label,white,16)+line(X(lo),y,X(hi),y,blue)+line(X(lo),y-7,X(lo),y+7,blue)+line(X(hi),y-7,X(hi),y+7,blue)+(point===null?'':circle(X(point),y,5,white))+text((X(lo)+X(hi))/2,y+27,`${lo.toLocaleString('en-US')}–${hi.toLocaleString('en-US')}`,gray,14,'middle');}).join('')+[0,max/2,max].map(n=>text(X(n),300,n.toLocaleString('en-US'),gray,14,'middle')).join('')),
(cost?'Established mould; approximately 20–50 hulls. Excludes tooling, engineering, development testing, freight, tax and supplier profit.':'Includes skins, core, hatch allowance, bonds, local reinforcement, inserts and finish. Excludes propulsion and onboard equipment.')+' Ranges are preliminary planning estimates, not confidence intervals. White circles mark central allowances; no hybrid central value is supplied.');}
if(name==='fuel-layout')return figure(svg('Fuel packaging direction and target CG datum',270,
 text(35,32,'TRANSOM / 0%',white)+text(645,32,'BOW / 100%',white,16,'end')+line(35,76,645,76)+path('M637 71L645 76L637 81',gray)+
 line(35+610*.38,58,35+610*.38,104,blue)+line(35+610*.42,58,35+610*.42,104,blue)+text(279,134,'38–42% working LCG window',blue,16,'middle')+
 text(35,191,'Pump ← drive / engine ← fuel tank',white,20)+text(35,221,'Relative order only · tank ahead of engine · final stations open',gray,15)),
 'Distance increases forward from the transom. The source’s 38–42% window is a mass-model hypothesis, not a measured CG or a tank installation coordinate. No hull outline or component spacing is implied.');
if(name==='fuel-levers')return figure(svg('Illustrative fuel lever arms about a fixed non-fuel centre of gravity',330,[['Fuel aft',135],['Fuel near reference',325],['Fuel forward',555]].map(([s,x],i)=>{let y=60+i*95;return text(30,y-20,s,white)+line(40,y,640,y)+line(340,y-25,340,y+20,gray,'4 4')+circle(x,y,7)+line(Math.min(x,340),y+24,Math.max(x,340),y+24,blue);}).join('')+text(340,322,'Dashed marker = reference CG · blue = fuel centroid',gray,14,'middle')),'Concept comparison only. A greater separation creates a greater fuel mass moment about the same reference. No trim, planing or porpoising result is calculated.');
if(name==='fuel-migration'){const x=f=>65+f/.2*570,y=d=>160-d/.03*105;return figure(svg('Illustrative CG migration with fuel mass fraction',335,
text(65,22,'COMBINED CG SHIFT / fraction of hull length',blue,14)+[-.03,0,.03].map(v=>line(65,y(v),635,y(v),'#2b3940')+text(52,y(v)+5,v.toFixed(2),gray,13,'end')).join('')+[0,.05,.1,.15,.2].map(f=>text(x(f),294,`${Math.round(f*100)}%`,gray,14,'middle')).join('')+[-.15,0,.15].map((d,i)=>line(x(0),y(0),x(.2),y(.2*d),[gray,white,blue][i])).join('')+text(350,325,'Fuel mass / total mass (including rider)',gray,14,'middle')),
 'Illustration: fixed non-fuel CG at 40% of length; fuel at 25% (gray), 40% (white) or 55% (blue), measured from the transom. ΔCG / length = fuel mass fraction × centroid separation / length. These are hypothetical inputs, not Wahoo masses or a tank model.');}
if(name==='fuel-access')return figure(flow([['Dedicated access','Tank removal path above its own station'],['Engine retained','Service the tank without extracting the engine'],['Fuel controlled','Baffles or compatible foam under review'],['Connections accessible','Pickup, venting, fittings and retention to resolve']]),'Service requirements replacing the source’s illustrative hatch drawing. Final hatch size, tank geometry and removal clearances remain open.');
if(name==='engine-arrangement')return figure(svg('Perpendicular cylinder and crankshaft axes',300,
line(60,175,620,175,blue)+path('M610 169L620 175L610 181')+line(270,230,270,45,white)+path('M264 55L270 45L276 55',white)+circle(270,175,9)+text(290,63,'Cylinder axis / across hull',white)+text(385,207,'Crankshaft → pump axis',blue)+text(40,275,'Axis relationship only · actual interior sections govern fit',gray,16)),
 'The cylinder is approximately transverse when the crankshaft follows the pump axis. Static, moving and service envelopes must all fit. Tank and exhaust positions are handled separately; this is not a hull layout.');
if(name==='engine-datums')return figure(svg('Nominal slider crank at top dead centre',330,'<g transform="translate(20 0)">'+
line(35,190,625,190,gray,'5 5')+circle(75,190,81.75,gray)+circle(75,190,5)+circle(156.75,190,5)+line(156.75,190,462.75,190,white)+circle(462.75,190,12)+line(546.75,145,546.75,235,blue)+line(383.25,145,383.25,235,gray,'4 4')+
line(75,65,546.75,65,blue)+text(311,50,'157.25 mm / crown datum at TDC',blue,17,'middle')+text(310,166,'Rod L = 102 mm REF',white,16,'middle')+text(499,125,'H = 28 REF',gray,14,'middle')+text(75,295,'r = 27.25 mm',gray,15)+text(420,295,'Stroke = 54.50 mm',gray,15)+'</g>'),
 'Source: engine report, WHE 001 Rev B. Centres and nominal distances only, at a common scale. Rod length and crown datum require verification. No piston contour, cylinder deck or overall engine length is established.');
if(name==='engine-pin')return figure(svg('Gudgeon pin reference geometry and piston crown datum',260,
text(35,28,'PISTON CROWN DATUM / UNCONFIRMED',blue,13)+line(45,75,230,75,gray,'4 4')+circle(135,159,18)+line(260,75,260,159,blue)+text(280,114,'28 mm REF',white)+text(35,218,'Crown contour and gauge point required',gray,14)+
circle(505,108,45)+circle(505,108,30,gray)+text(505,188,'WP032: Ø15 / Ø10 mm',white,16,'middle')+text(505,219,'45 mm length · source reference',gray,14,'middle')),
 'The report identifies WP032 with the selected piston kit. Its nominal wall is (15 − 10) / 2 = 2.5 mm. Catalogue references must be checked on the supplied part; no fits or tolerances are released.');
if(name==='engine-crowns')return figure(svg('Three illustrative piston crown forms',200,[['Flat','M0 0L150 0'],['Domed','M0 0Q75 -55 150 0'],['Dished','M0 0Q75 50 150 0']].map(([t,d],i)=>`<g transform="translate(${35+i*220} 95)">${path(d)}${text(75,-65,t,white,18,'middle')}${line(0,0,0,55,gray)}${line(150,0,150,55,gray)}</g>`).join('')),
 'Illustrative forms only. The exact 8160DA crown is unconfirmed. Chamber volume, squish geometry and the head must follow the actual crown; none of these curves is a proposed supplier profile.');
if(name==='engine-rod')return figure(svg('Connecting rod centre-distance reference',260,
circle(125,135,58,gray)+circle(533,135,38,gray)+line(125,135,533,135,white,'4 4')+line(125,50,533,50,blue)+text(329,32,'102 mm centre distance / working reference',blue,16,'middle')+text(125,229,'Big-end eye Ø29 REF',gray,15,'middle')+text(533,229,'Small-end eye Ø19 REF',gray,15,'middle')),
 'Source: P2018 references within the engine report. Eye bores are not pin diameters. Their dimensions and bearing stack need verification; external rod geometry is deliberately omitted.');
if(name==='engine-motion')return figure(motionChart()+motionChart(true)+`<details><summary>Calculated samples and assumptions</summary><div class="table-scroll"><table><thead><tr><th>Angle (°)</th><th>Travel (mm)</th><th>Velocity (m/s)</th></tr></thead><tbody>${[0,45,90,135,180,225,270,315,360].map(a=>{let p=pistonSample(a);return `<tr><td>${a}</td><td>${p.x.toFixed(2)}</td><td>${p.v.toFixed(2)}</td></tr>`;}).join('')}</tbody></table></div><p>Rigid zero-offset slider crank: r = 27.25 mm; L = 102 mm; 12,000 rpm. x = r(1 − cos θ) + L − √(L² − r² sin² θ). Velocity is its time derivative. Curves sampled every degree.</p></details>`,
 'Recalculated from the source geometry, not digitised from its graph. Travel increases away from TDC; negative velocity returns toward TDC. Mean speed 21.80 m/s; peak approximately 35.45 m/s. No elastic, thermal or bearing-clearance effects.');
if(name==='engine-crank')return figure(flow([['Rotor end','Taper, key, thread and axial position open'],['Bearing interfaces','Journal diameters, shoulders and fits required'],['Webs + rod','Sweep, pack width, side clearance and masses required'],['Drive end','Coupling and separate pump-thrust path to define']]),'Interface register replacing WHE 003’s schematic shaft outline. Earlier custom-crank web and journal assumptions are not dimensions of the purchased CS2018.');
if(name==='engine-ports')return figure(svg('Unwrapped port relationship concept',300,
line(40,40,640,40,gray,'4 4')+text(640,27,'Deck datum',gray,14,'end')+line(40,245,640,245,gray,'4 4')+text(640,277,'BDC reference',gray,14,'end')+path('M60 245V165H165V245M270 245V95H415V245M520 245V165H625V245',white)+text(112,222,'T',blue,24,'middle')+text(342,222,'E',blue,24,'middle')+text(572,222,'T',blue,24,'middle')+line(215,65,215,245,blue,'5 5')+text(215,294,'Example ring-peg path',gray,14,'middle')),
 'Concept only, after WHE 004. E = exhaust, T = transfer. No port width, height, angle or ring-peg position is selected. Opening timing alone does not establish time-area, flow capacity or ring support.');
if(name==='engine-gas')return figure(flow([['Outside air','Water separation and throttle'],['Reed → crankcase','Proposed reed-inducted air route'],['Transfer → cylinder','Charge delivery through the ports'],['Tuned exhaust','Develop with port events and pump load']]),'Functional gas path. EFI location and lubrication remain open: upstream, transfer or direct injection require different arrangements. Direct injection would not remove the scavenging-air requirement.');
if(name==='engine-cooling')return figure(`<h3>Option 1 / Raw water</h3>${flow([['Pickup + strainer','Supply across the operating range'],['Engine jacket','Heat pickup and monitoring'],['Discharge','Accessible flushing and drainage']])}<h3>Option 2 / Isolated engine loop</h3>${flow([['Raw-water side','Feeds heat exchanger'],['Heat exchanger','Transfers heat between separate circuits'],['Engine coolant loop','Circulation pump, jacket and return']])}`,
 'Alternative architectures from the new report; neither is selected. Arrows and sequence denote functions only, not a released piping circuit. Cooling pressures, flow rates, temperatures and corrosion provisions remain to be engineered.');
if(name==='engine-sequence')return figure(flow([['Verify interfaces','Supplier drawings or exact-part metrology'],['Freeze moving assembly','Confirm datums, travel, masses and fit'],['Develop the systems','Ports, head, cases, EFI, exhaust and cooling'],['Test and inspect','Bench → dyno → installed hull → teardown']]),'An iterative sequence. Test evidence may send the design back to earlier stages. No completed-test status or release date is implied.');
return '';
}
